### PR TITLE
Add client side validations

### PR DESCRIPTION
**Pull request by ShIxtan**
Hello!

I've been using zxcvbn.net, and have been wanting to add client-side validations that include the generated suggestions. It wasn't working however, because the version of zxcvbn.js included here doesn't have those warnings, and the new version has a slightly different scoring algorithm. So I hope you don't mind I made a few suggested changes to support the newer version here, and added in those client-side validations.

Please let me know if there is anything you don't like, or have questions about. Thanks for a great library!

### CODE REVIEW

**Comment by darcythomas** [comment]
Hmmm a bit of a breaking change. That's OK the parent lib started it.

I will will review when I can get in front if a PC.

**Comment by darcythomas** [comment]
@ShIxtan  I have had a look (Sorry for the delay).

Looks good apart from the bin files that have been included. Can you remove them/ update the .gitignore file to exclude them.

**Comment by ShIxtan** [comment]
Sorry for the delay!

I removed the two .nupkg files that were generated in the build, sorry about that! the other bin that was modified is NuGet.exe, but that one seems to be required by the build scripts, so I didn't want to mess with it.

Let me know if there is anything else I can help with!

**Comment by darcythomas** [comment]
Sorry only just got back to this. _Puts on cone of shame_. I'll try sort this weekend

**Pull request closed without merging**
